config/routes.rb
FeedasaurusRails::Application.routes.draw do
  root :to => 'feeds#index'

  resources :feeds, only: [:index, :show] do
    post :subscribe, on: :collection
    get :refresh, on: :member
  end
  resources :items, only: [:show]
  resources :groups, only: [:index]

  mount FeverAPI => '/api/fever'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :author, :body, :fetched_at, :read_at, :starred_at, :title, :url
  belongs_to :feed

  default_scope order('created_at DESC')

  scope :read, -> { where('read_at IS NOT NULL') }
  scope :unread, -> { where('read_at IS NULL') }
  scope :starred, -> { where('starred_at IS NOT NULL') }
  scope :unstarred, -> { where('starred_at IS NULL') }

  def self.find_by_url(url)
    where(url: url)
  end

  def mark_as_read
    update_attribute(:read_at, Time.current)
  end

  def mark_as_unread
    update_attribute(:read_at, nil)
  end

  def mark_as_starred
    update_attribute(:starred_at, Time.current)
  end

  def mark_as_unstarred
    update_attribute(:starred_at, nil)
  end

  # Returns whether an item has been read.
  def read?
    not read_at.nil?
  end

  # Returns whether an item has been starred.
  def starred?
    not starred_at.nil?
  end

  def exists?
    persisted? ||
      self.class.find_by_url(url).exists?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/show.html.erb
<div id="feeds">
  <ul>
    <li class="feed"><%= link_to @item.feed.title, feeds_path %></li>
  </ul>
</div>

<div id="items">
  <ul>
    <li class="feed-item"><%= link_to @item.title, @item.feed %></li>
  </ul>
</div>

<div id="item">
  <p>Published: <%= link_to format_time(@item.created_at), @item.url %></p>
  <article id="item-content">
    <%= @item.content.html_safe %>
  </article>
</div>